# Generated by Django 5.2.5 on 2025-09-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
    ]
