# Generated by Django 5.2.5 on 2025-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='avg_delay_hours',
            field=models.FloatField(default=0.0, help_text='Average delay in hours'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='on_time_percent',
            field=models.FloatField(default=0.0, help_text='Percent of on-time deliveries (0-100)'),
        ),
    ]
