# Generated by Django 5.2.5 on 2025-09-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_order_created_at_order_delay_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delay_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
