# Generated by Django 5.2.5 on 2025-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0003_alter_order_delay_minutes_alter_order_order_id_and_more'),
        ('vendors', '0003_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date', 'id'], name='order_date_id_idx'),
        ),
    ]
